---
- name: Enable IIS Web Server role
  ansible.windows.win_feature:
    name: Web-Server
    state: present
    include_management_tools: yes

- name: Enable IIS additional features
  ansible.windows.win_feature:
    name:
      - Web-Http-Logging
      - Web-Request-Monitor
      - Web-Http-Tracing
      - Web-Stat-Compression
      - Web-Filtering
      - Web-CGI
      - Web-ISAPI-Ext
      - Web-ISAPI-Filter
      - Web-Net-Ext45
      - Web-Asp-Net45
      - Web-Windows-Auth
    state: present

- name: Ensure W3SVC is running
  ansible.windows.win_service:
    name: W3SVC
    state: started
    start_mode: auto
